version: "3.9"

services:
  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]

  apache:
    image: apache-otel-demo_apache:latest
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./otel:/usr/local/apache2/otel  # Lua script folder
    depends_on:
      - otel-collector

  flask-app:
    image: apache-otel-demo_app:latest
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - otel-collector
