ServerRoot "/usr/local/apache2"
Listen 80

# Event MPM and Lua
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule lua_module modules/mod_lua.so
LoadModule headers_module modules/mod_headers.so

# Required for 'Require all granted'
LoadModule authz_core_module modules/mod_authz_core.so

DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    AllowOverride None
    Require all granted
</Directory>

# Enable Lua OTEL tracing
LuaHookFixups "/usr/local/apache2/otel/otel.lua" trace_request

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common
